parameters:
  # Env. Variables
  consumer_key: '%env(CONSUMER_KEY)%'
  consumer_secret: '%env(CONSUMER_SECRET)%'
  access_token: '%env(ACCESS_TOKEN)%'
  access_secret: '%env(ACCESS_SECRET)%'
  redis_addr: '%env(REDIS_ADDR)%'

services:
#    retweet_blockchain.example:
#        class: RetweetBot\RetweetBlockchainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  fetch.tweets.abraham.twitteroauth:
    class: RetweetBot\RetweetBlockchainBundle\Services\AbrahamTwitterOAuthWrapper
    arguments: ['@abraham.twitteroauth']

  retweetbot.redis:
    class: RetweetBot\RetweetBlockchainBundle\Services\RedisWrapper
    arguments: ['%redis_addr%']